### PR TITLE
V2 nd subs

### PR DESCRIPTION
**Pull request by ai-nick**
this contains code for >2 dimensional substrates using es-hyperneat and the pruning_and_extraction indent

### CODE REVIEW

**Comment by ukuleleplayer** [comment]
Can you show me an experiment utilizing this n-dimensional hypercube?

**Comment by ai-nick** [comment]
hey yes I do, located here: https://github.com/nickwilliamsnewby/cryptochronolonic/tree/better_inputs  I am currently working on double checking everything, sebastian risi will be reviewing at some point the whole lib  to verify whether the code additions i made are valid or not.

**Comment by ai-nick** [comment]
I have a c9 instance ill pull all the latest branches into so you can run a couple generations without the lengthy install lol

**Comment by ai-nick** [comment]
3d_confirmed_hiddenevo

this is a network that is evolving right now, all input is in the center with output positioned in the front center and hidden nodes are everything else

**Pull request closed without merging**
