### PR TITLE
lines 132 thru 141 in es_hyperneat should be nested in the else statm…

### PR DESCRIPTION
**Pull request by ai-nick**
…ent on line 126, now you can change max depth without getting none type errors

### CODE REVIEW

**Comment by ukuleleplayer** [comment]
Hi Nick,
I've tried with and without your fix - it does not seem to give me a none type error in neither of the cases?

**Comment by ai-nick** [comment]
I only noticed it when I changed the max depth above one which then allows it it to query using the quad tree until varience is below threshold or max depth is met, without indenting the block I got errors do to the [None]*4 inititilization of quadtree children

**Comment by ai-nick** [comment]
right now im trying to figure out how to write a tree to handle n dimension since the java, c++, c#, and other python libraries (the psuedocode in the paper as well) will only support querying two dimensional substrate coordinates (the java and c++ versions have psuedo 3d support) so if you have any suggestions or advice feel free to hit me up, I would like to implement this across all the packages but im starting here :)

**Comment by ukuleleplayer** [comment]
Can you show me an experiment with the error? I tried changing the max depth as well and there were 0 errors.
When you say 3D, you wanna create the input/output nodes as 3D coordinates and the internal substrate should follow these dimensions?

**Comment by ai-nick** [comment]
Correct so the cppn would search a hypercube of twice that, Kent makes some comments about this in the hyperneat paper, I'll send over my setup that gave me the error when I get home

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by ai-nick** [comment]
the experiment I was running is found in my repo cryptochronolonic and the file is trading_purples.py the branch running-version or v1.1.2 should run giving all dependencies are installed, so if you switch to master and install pureples it will fail during pruning and extraction but if you switch to the branch with the block that i nested under the first if statement in pruning and extraction it will running as expected. here is a link
https://github.com/nickwilliamsnewby/cryptochronolonic

**Comment by ai-nick** [comment]
also I had to create a v-3 branch for neat-python that you should pull down and install or else it wont run

**Comment by ukuleleplayer** [comment]
I will need a minimum working example if I am to test, what you are saying - I can't do it in your repository. 
Can you do it with XOR maybe?

**Comment by ai-nick** [comment]
Ill try that, if I cant I will send a c9.io link with an experiment in which it fails, it occurs when you reach pruning_and_extraction and the if statement in line 124 of es-hyperneat.py evaluates true, thus skipping the assignments in lines 127-130 causing a none type error on line 133 since the variables in that if statement are still none-type

**Comment by ukuleleplayer** [comment]
I'll close this and wait for your pull request containing it all.

**Pull request closed without merging**
