### PR TITLE
Version three compat

### PR DESCRIPTION
**Pull request by ai-nick**
some changes to support python 3

### CODE REVIEW

**Comment by ukuleleplayer** [comment]
Hi Nick,
Thanks for the PR, really appreciate it!
A questions and two requests:
1. Why did you entirely remove 6 lines of code in pureples/experiments/xor/es_hyperneat_xor_small.py?
2. Could you please modify the pureples/setup.py to reflect the changes?
3. Could you please preserve compatibility with Python 2.7 throughout the PR by checking the Python version, catching import errors etc.?

Cheers and thanks again,
Adrian

**Comment by ai-nick** [comment]
hey sorry i had copied that experiment to as a template of sorts for my own experiment, i just pushed up a new commit with the original, this doesnt have #3 done yet if you dont mind im going to leave it open so I remember to do it but you can ignore until i make another commit with a message confirm 2 compat is safu

**Comment by ukuleleplayer** [comment]
Hi again Nick,

You still seem to be modifying files which shouldn't be modified. 
Furthermore, please refrain from doing stuff like `os.environ["PATH"] += os.pathsep + 'D:/Program Files (x86)/Graphviz2.38/bin/'` as it is only valid on _your_ machine.

Kind regards

**Comment by ai-nick** [comment]
Hey yeah sorry about that, just trying to get my external experiment to work, I am going to close my pr and branch off main into a fresh branch to do the version3 compatibility update, i think changing print to print() will be version 2 compatible still, but the changes of xrange to range dropping the cPickle import and wrapping ranges with list() will be done conditionally on new branch.

**Pull request closed without merging**
